version: "3.5"
services:

  backend:
    build:
      context: .
    depends_on: 
      - db
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && vote"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/vote
    expose:
      - "8080"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: front/
    depends_on:
      - backend
    expose:
      - "80"
    ports:
      - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vote
    ports:
      - "5432:5432"
